security:
    encoders:
        BackendBundle\Entity\User: {algorithm: sha512, encode_as_base64: true, iterations: 10}

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN: [ROLE_SUPERVISOR,ROLE_INSPECTOR,ROLE_ALLOWED_TO_SWITCH]
        ROLE_INSPECTOR: [ROLE_SUPERVISOR,ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: BackendBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        registro:
            pattern:  /registro
            security: false
        backend_login:
            pattern:  ^/admin/login$
            security: false

        backend:
            pattern:        ^/admin
            provider:       users
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin
                always_use_default_target_path: true
            logout:
                path: _admin_logout
                target: _admin_login



    access_control:
        - { path: ^/*, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_ADMIN]}

