# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.mailer.transport: sendmail

services:
    app.mailer:
        class:        BackendBundle\Services\Mailer
        arguments:    ['%app.mailer.transport%']

    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }
