<?php

namespace BackendBundle\Repository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends \Doctrine\ORM\EntityRepository
{

    public function findBannersLimit($limit){
        $qb = $this->createQueryBuilder("l")
            ->select('n')
            ->from("BackendBundle:Banner", "n")
            ->setFirstResult(0) ->setMaxResults($limit)
            ->orderBy('n.fecha', 'DESC')
            ->getQuery();

        return $qb->getResult();

    }
}
