<?php

namespace BackendBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends \Doctrine\ORM\EntityRepository
{

    public function findBannersLimit($limit){
        $em = $this->getEntityManager();
        $qb = new QueryBuilder($em);
        $qb->add('select', 'u')
            ->add('from', 'BackendBundle:Banner u')
            ->where("u.sitio_web = 'Egauss Holding'")
            ->add('orderBy', 'u.fecha DESC')
            ->setFirstResult( 0 )
            ->setMaxResults( $limit );
        $query = $qb->getQuery();
        return $query->getResult();

    }
    public function findBannersLimitGlobal($limit){

        $em = $this->getEntityManager();
        $qb = new QueryBuilder($em);
        $qb->add('select', 'u')
            ->add('from', 'BackendBundle:Banner u')
            ->where("u.sitio_web = 'Global ImasT'")
            ->add('orderBy', 'u.fecha DESC')
            ->setFirstResult( 0 )
            ->setMaxResults( $limit );
        $query = $qb->getQuery();
        return $query->getResult();

    }
}
