<?php

namespace BackendBundle\Repository;
use Doctrine\ORM\QueryBuilder;
use AppBundle\DQL\RandFunction;

/**
 * ColaboradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColaboradorRepository extends \Doctrine\ORM\EntityRepository
{

    public function findColaboradoresLimit($limit){
        $em = $this->getEntityManager();
        $offset = intval(rand(0, $this->getCount() - 1));
        $qb = new QueryBuilder($em);
        $qb->add('select', 'u')
            ->add('from', 'BackendBundle:Colaborador u')
            ->setFirstResult($offset)
            ->setMaxResults( $limit );
        $query = $qb->getQuery();
        return $query->getResult();

    }

    public function getRandomEntities($count = 3)
    {
        return  $this->createQueryBuilder('q')
            ->addSelect('RAND() as HIDDEN rand')
            ->addOrderBy('rand')
            ->setMaxResults($count)
            ->getQuery()
            ->getResult();
    }

    public function getCount()
    {
        $qb = $this->createQueryBuilder('i')
            ->select('COUNT(i.id)')
            ->getQuery()->getSingleScalarResult();
        return $qb;
    }
}
