<?php

namespace BackendBundle\Repository;

/**
 * ColaboradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColaboradorRepository extends \Doctrine\ORM\EntityRepository
{
}
