<?php

namespace BackendBundle\Repository;

/**
 * ColaboradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColaboradorRepository extends \Doctrine\ORM\EntityRepository
{

    public function findColaboradoresLimit($limit){
        $qb = $this->createQueryBuilder("l")
            ->select('n')
            ->from("BackendBundle:Colaborador", "n")
            ->setFirstResult(0) ->setMaxResults($limit)
            ->getQuery();

        return $qb->getResult();

    }
}
