<?php

namespace BackendBundle\Repository;

/**
 * PaginaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DondeEstamosRepository extends \Doctrine\ORM\EntityRepository
{
}
