<?php

namespace BackendBundle\Repository;

/**
 * EcosistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcosistemaRepository extends \Doctrine\ORM\EntityRepository
{
}
