<?php

namespace BackendBundle\Repository;

/**
 * EdicionAnteriorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdicionAnteriorRepository extends \Doctrine\ORM\EntityRepository
{
}
