<?php

namespace BackendBundle\Repository;

/**
 * Global2016Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Global2016Repository extends \Doctrine\ORM\EntityRepository
{
}
