<?php

namespace BackendBundle\Repository;

/**
 * MisionVisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MisionVisionRepository extends \Doctrine\ORM\EntityRepository
{
}
