<?php

namespace BackendBundle\Repository;

/**
 * NoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends \Doctrine\ORM\EntityRepository
{

    public function findNoticiasLimit($limit){
        $qb = $this->createQueryBuilder("l")
            ->select('n')
            ->from("BackendBundle:Noticia", "n")
            ->setFirstResult(0) ->setMaxResults($limit)
            ->getQuery();

        return $qb->getResult();

    }
    public function findNoticiasGlobalLimit($limit){
        $qb = $this->createQueryBuilder("l")
            ->select('n')
            ->from("BackendBundle:Noticia", "n")
            ->where("n.owner = 'global-imast'")
            ->setFirstResult(0) ->setMaxResults($limit)
            ->getQuery();

        return $qb->getResult();

    }
}
