<?php

namespace BackendBundle\Repository;

/**
 * QueEsGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueEsGlobalRepository extends \Doctrine\ORM\EntityRepository
{
}
