<?php

namespace BackendBundle\Repository;

/**
 * QuienesSomosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuienesSomosRepository extends \Doctrine\ORM\EntityRepository
{
}
