<?php

namespace BackendBundle\Repository;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
