<?php

namespace BackendBundle\Repository;

/**
 * SolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolucionRepository extends \Doctrine\ORM\EntityRepository
{
}
