<?php

namespace BackendBundle\Repository;

/**
 * VideoColaboradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoColaboradorRepository extends \Doctrine\ORM\EntityRepository
{
}
