<?php

namespace BackendBundle\Repository;

/**
 * PaginaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{

    public function findVideosLimit($limit){
        $qb = $this->createQueryBuilder("l")
            ->select('n')
            ->from("BackendBundle:Video", "n")
            ->where("n.sitio_web ='Egauss Holding'")
            ->andWhere("n.inhomepage = '1'")
            ->setFirstResult(0) ->setMaxResults($limit)
            ->getQuery();

        return $qb->getResult();

    }
    public function findVideosGlobalLimit($limit){
        $qb = $this->createQueryBuilder("l")
            ->select('n')
            ->from("BackendBundle:Video", "n")
            ->where("n.sitio_web ='Global ImasT'")
            ->andWhere("n.inhomepage = '1'")
            ->setFirstResult(0) ->setMaxResults($limit)
            ->getQuery();

        return $qb->getResult();

    }
}
