<?php

namespace BackendBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * PaginaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{

    public function findVideosLimit($limit){

        $em = $this->getEntityManager();
        $qb = new QueryBuilder($em);
        $qb->add('select', 'u')
            ->add('from', 'BackendBundle:Video u')
            ->where("u.sitio_web = 'Egauss Holding'")
            ->andWhere("u.inhomepage = '1'")
            ->setFirstResult( 0 )
            ->setMaxResults( $limit );
        $query = $qb->getQuery();
        return $query->getResult();

    }
    public function findVideosGlobalLimit($limit){
        $em = $this->getEntityManager();
        $qb = new QueryBuilder($em);
        $qb->add('select', 'u')
            ->add('from', 'BackendBundle:Video u')
            ->where("u.sitio_web = 'Global ImasT'")
            ->andWhere("u.inhomepage = '1'")
            ->setFirstResult( 0 )
            ->setMaxResults( $limit );
        $query = $qb->getQuery();
        return $query->getResult();

    }
}
